site_name: Warframe Model Resources Guides
theme:
  logo: assets/icons/transparent-logo.gif #wonder how this affects performance
  name: material
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - toc.follow
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: pink
      accent: deep orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep orange

repo_name: Puxtril/Warframe-Exporter
repo_url: https://github.com/Puxtril/Warframe-Exporter

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Puxtril
    - icon: fontawesome/brands/github
      link: https://github.com/Kptweedy
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Jk3xA2T
    - icon: simple/mega
      link: https://mega.nz/folder/fIUQDQYZ#vRNqurxNdzELIboK214Kxg

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      
plugins:
  - search
  - open-in-new-tab

# Page tree
nav:
  - Home: 
    - index.md
    - Contributing: contributing.md
    - Site Layout: layout.md
  - Warframe Guides:
    - wf-guides/index.md
    - Extractor:
      - wf-guides/extractor/index.md
      - Useful Tools: wf-guides/extractor/tools.md
      - Warframe Directory layout: wf-guides/extractor/file-list.md
    - Shaders:
      - wf-guides/shaders/index.md
      - Pruu Shaders: 
        - wf-guides/shaders/pruu/index.md
        - Detail Names: wf-guides/shaders/pruu/details.md
      - Valk Shaders: wf-guides/shaders/valk-shader.md
      - Baking Textures: wf-guides/shaders/baking.md
    - Models:
      - How To Use Curated Models:  wf-guides/model-usage.md
      - How To Set Up Models In Blender: wf-guides/model-setup.md
  - Curated Models and Resources: https://mega.nz/folder/fIUQDQYZ#vRNqurxNdzELIboK214Kxg
  - Warframe Model Resources Discord: https://discord.gg/Jk3xA2T
  - Inspiration Gallery:
    - inspiration-gallery/index.md