site_name: Warframe Model Resources Knowledge Base
theme:
  logo: assets/icons/new-logo-better.svg #wonder how this affects performance
  name: material
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
    admonition:
      note: material/pencil-circle
      abstract: material/clipboard-text
      info: material/information
      tip: material/fire
      success: material/check
      question: material/help-circle
      warning: material/alert
      failure: material/close
      danger: material/lightning-bolt-circle
      bug: material/shield-bug
      example: material/test-tube
      quote: material/format-quote-close
      youtube: material/youtube

  features:
    - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.footer
    - toc.follow
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette: 
    # scheme: custom
    # primary: custom

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: pink
      accent: deep orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep orange

repo_name: Puxtril/Warframe-Exporter
repo_url: https://github.com/Puxtril/Warframe-Exporter/releases
copyright: Not affiliated with Digital Extremes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Puxtril
    - icon: fontawesome/brands/github
      link: https://github.com/Kptweedy
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Jk3xA2T
    - icon: simple/mega
      link: https://mega.nz/folder/fIUQDQYZ#vRNqurxNdzELIboK214Kxg

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde  
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      
plugins:
  - search
  - open-in-new-tab
  - glightbox

# Page tree
nav:
  - Home: 
    - index.md
    - Contributing: contributing.md
    - Frequently Asked Questions: wf-guides/faq.md
  - Warframe Guides:
    - wf-guides/index.md
    - Frequently Asked Questions: wf-guides/faq.md
    - Extractor:
      - Internal Name Index: wf-guides/extractor/file-list.md
      - Using The Extractor: wf-guides/extractor/extractor.md
      - Useful Tools & Scripts: wf-guides/extractor/tools.md
    - Models:
      - wf-guides/models/index.md
      - How to set up Characters in Blender: wf-guides/models/character-setup.md
      - How to set up Weapons in Blender: wf-guides/models/weapon-setup.md
      - How to set up Levels in Blender: wf-guides/models/level-setup.md
    - Shaders:
      - wf-guides/shaders/index.md
      - Baking Textures: wf-guides/shaders/baking.md
      - Pruu Shaders: 
        - wf-guides/shaders/pruu/index.md
        - Detail Names: wf-guides/shaders/pruu/details.md
      - Valkyrie Shaders: wf-guides/shaders/valk-shader.md
  - Curated Models and Resources: https://mega.nz/folder/fIUQDQYZ#vRNqurxNdzELIboK214Kxg
  - Warframe Model Resources Discord: https://discord.gg/Jk3xA2T
  - Inspiration Gallery:
    - inspiration-gallery/index.md